### ISSUE TITLE
[Feature Request] Implement Download Speed Limiting to Prevent Throttling

### ISSUE THREAD

**Issue by uprprc777** [1n0r1/monster-siren-download#6]
When using the “Download ALL!” feature, there is a high likelihood that Hypergryph’s servers will throttle the connection. If throttling occurs, the connection may be forcibly terminated, leading to incomplete data transfer. In such cases, the python script will crash.

To address this issue, consider implementing a download speed limit. For instance, introducing a delay after a set number of downloads could prevent throttling. Additionally, improving the script’s exception handling would be advantageous. This could involve managing connection errors more effectively and retrying downloads if an error occurs.

**Comment by uprprc777** [comment]
Python error message when connection terminated by Hypergryph’s servers, FYI.

```
multiprocessing.pool.RemoteTraceback:
"""
Traceback (most recent call last):
  File "****\Python\Python311\site-packages\urllib3\response.py", line 748, in _error_catcher
    yield
  File "****\Python\Python311\site-packages\urllib3\response.py", line 894, in _raw_read
    raise IncompleteRead(self._fp_bytes_read, self.length_remaining)
urllib3.exceptions.IncompleteRead: IncompleteRead(**** bytes read, **** more expected)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "****\Python\Python311\site-packages\requests\models.py", line 820, in generate
    yield from self.raw.stream(chunk_size, decode_content=True)
  File "****\Python\Python311\site-packages\urllib3\response.py", line 1060, in stream
    data = self.read(amt=amt, decode_content=decode_content)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "****\Python\Python311\site-packages\urllib3\response.py", line 949, in read
    data = self._raw_read(amt)
           ^^^^^^^^^^^^^^^^^^^
  File "****\Python\Python311\site-packages\urllib3\response.py", line 872, in _raw_read
    with self._error_catcher():
  File "C:\Program Files\Python311\Lib\contextlib.py", line 158, in __exit__
    self.gen.throw(typ, value, traceback)
  File "****\Python\Python311\site-packages\urllib3\response.py", line 772, in _error_catcher
    raise ProtocolError(arg, e) from e
urllib3.exceptions.ProtocolError: ('Connection broken: IncompleteRead(**** bytes read, **** more expected)', IncompleteRead(**** bytes read, **** more expected))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files\Python311\Lib\multiprocessing\pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
                    ^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python311\Lib\multiprocessing\pool.py", line 48, in mapstar
    return list(map(*args))
           ^^^^^^^^^^^^^^^^
  File "****\monster-siren-download-main\main.py", line 187, in download_album
    filename, filetype = download_song(session=session, directory=directory + make_valid(album_name), name=song_name, url=song_sourceUrl)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "****\monster-siren-download-main\main.py", line 116, in download_song
    for data in source.iter_content(chunk_size = 1024):
  File "****\Python\Python311\site-packages\requests\models.py", line 822, in generate
    raise ChunkedEncodingError(e)
requests.exceptions.ChunkedEncodingError: ('Connection broken: IncompleteRead(**** bytes read, **** more expected)', IncompleteRead(**** bytes read, **** more expected))
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "****\monster-siren-download-main\main.py", line 234, in <module>
    main()
  File "****\monster-siren-download-main\main.py", line 226, in main
    pool.map(download_album, albums)
  File "C:\Program Files\Python311\Lib\multiprocessing\pool.py", line 367, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python311\Lib\multiprocessing\pool.py", line 774, in get
    raise self._value
requests.exceptions.ChunkedEncodingError: ('Connection broken: IncompleteRead(**** bytes read, **** more expected)', IncompleteRead(**** bytes read, **** more expected))
```

**Comment by 1n0r1** [comment]
Interesting. I believe they added this limit recently. I will try and see if I can replicate it and if the limit fix the limit.

**Comment by muelsyse-az** [comment]
Repeating the script solves this but I'm afraid a long term solution may be needed before Hypergryph implements a more severe throttle.

**Comment by sammy6345** [comment]
I'd forgotten to comment or make a pr when I'd made this change locally, but if you change main.py Line 233 with the following diff it caps the number of downloads that will be attempted simultaneously, as otherwise it makes a sub-process for each core in the cpu, meaning it will be hitting monster-siren potentially 8, 12, 16, 24 times at a time depending on your computer specs. Sure this doesn't throttle the download speed, but you are limiting the amount of connection requests that come in at once, making it look a bit less like spam.

```diff 
-    with Pool(maxtasksperchild=1) as pool:
+    with Pool(4, maxtasksperchild=1) as pool:
```
And yes, this had worked for me when I'd done my initial pull down of everything.
