### ISSUE TITLE
Pyaudioop not found

### ISSUE THREAD

**Issue by Seenthe** [1n0r1/monster-siren-download#8]
File "C:\Users\\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\pydub\utils.py", line 14, in <module>
    import audioop
ModuleNotFoundError: No module named 'audioop'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\\Downloads\monster-siren-download-main\main.py", line 12, in <module>
    from pydub import AudioSegment
  File "C:\Users\\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\pydub\__init__.py", line 1, in <module>
    from .audio_segment import AudioSegment
  File "C:\Users\\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\pydub\audio_segment.py", line 11, in <module>
    from .utils import mediainfo_json, fsdecode
  File "C:\Users\\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\pydub\utils.py", line 16, in <module>
    import pyaudioop as audioop
ModuleNotFoundError: No module named 'pyaudioop'

**Comment by Cyears** [comment]
Hey I had this problem too! After looking around for a while I found this post on [reddit](https://www.reddit.com/r/discordbots/comments/1grhj51/heres_my_code_but_when_i_try_to_run_it_i_have_the/)

In the comments, someone recommended to enter "pip install audioop-lts"

I tried this and it solved both issues of:
1. ModuleNotFoundError: No module named 'audioop' and 
2. ModuleNotFoundError: No module named 'pyaudioop'

Hope this works for you too
